cat("format of quadratic equation" , "ax^2 + bx + c")
print("enter values of a , b , c ")
a <- readline(prompt = "Enter a")
b <- readline(prompt = "Enter b")
c <- readline(prompt = "Enter c")
a <- as.integer(a)
b <- as.integer(b)
c <- as.integer(c)
mid <-  (b*b)-(4*a*c)
mid <-  mid**(1/2)
root1 <- ( - b + mid )/(2*a)
root2 <- ( - b - mid )/(2*a)

cat("root1 : ",root1)
cat("root2 : ",root2)