n1 <- as.integer(readline("enter 1st n0"))
n2 <- as.integer(readline("enter 2st n0"))
n3 <- as.integer(readline("enter 3st n0"))
n4 <- as.integer(readline("enter 4st n0"))
l <- c(n1,n2,n3,n4)
sort(l)
cat("3rd larges no is",l[3])
